name: base
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - requests
  - numba
  - numpy
  - pandas
  - scipy
  - matplotlib
  - ipywidgets
  - rise
  - pip:
    - watchdog
    - git+https://github.com/NumEconCopenhagen/NumEcon
